# Generated by Django 4.2.16 on 2024-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmainview',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shopmainview',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shopmainview',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shopmainview',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopmainview',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopmainview',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
