# Generated by Django 4.2.16 on 2024-11-23 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
